Record start of run
dqian3/wikipedia-speedruns pull request #33
Opened 2021-12-07 16:44 UTC by bricehalder

2021-12-22 01:08 UTC, dqian3 commented on apis/runs.py
> +    end_time = datetime.fromtimestamp(request.json['end_time']/1000) if 'end_time' in request.json else None
Also this would create 2 runs, would it not? Shouldn't we have an update somewhere?

2021-12-22 02:06 UTC, dqian3 requested changes
See the comment about the

2021-12-22 08:31 UTC, bricehalder commented on apis/runs.py
> +    end_time = datetime.fromtimestamp(request.json['end_time']/1000) if 'end_time' in request.json else None
Fixed

2021-12-22 08:51 UTC, bricehalder commented
Need to do `ALTER TABLE runs MODIFY path TEXT NULL;` on prod database.

Took out path for same reason as end time

2022-01-03 20:42 UTC, dqian3 commented
> Need to do `ALTER TABLE runs MODIFY path TEXT NULL;` on prod database.
> 
> Took out path for same reason as end time

Shouldn't this be changed in the scripts then?

2022-01-05 23:48 UTC, dqian3 approved these changes

2022-01-05 23:51 UTC, merged