Ongoing minor frontend updates
dqian3/wikipedia-speedruns pull request #82
Opened 2022-01-12 03:54 UTC by mliu59

Running PR for small front end changes such as typos, spacing, etc.

2022-01-17 19:00 UTC, dqian3 commented
I know we didn't go over bootstrap much yet, but in the future maybe try and do these kinds of things with Bootstrap to be more consistent.

2022-01-17 19:00 UTC, dqian3 approved these changes

2022-01-17 19:07 UTC, dqian3 requested changes
Actually, the twitter logo is a bit off, I merged the changes into [beta](beta.wikispeedruns.com)

2022-01-17 19:09 UTC, mliu59 commented
Currently working through those + a couple of mobile display fixes

2022-01-19 18:06 UTC, dqian3 approved these changes

2022-01-19 18:06 UTC, merged